### ISSUE TITLE
As a user I want a Setup Tab

### ISSUE THREAD

**Issue by synasius** [evonove/volfyirion-app#1]
<img width="375" alt="SETUP" src="https://user-images.githubusercontent.com/217898/58614855-e0960700-82b9-11e9-9d5a-8947198f81db.png">

# Description
As a user I want a Setup Tab to access `Game Setup`, `Rulebook` and `Growl`. Section provides a `StackView` where subpages are pushed.

# Depends on
- [x] #5 Create volfyirion style
- [x] #2 Create button component
- [x] #3 Create growl button component
- [x] #4 Create TabBar and TabButton component

# Assets

Logo
![logo_gold](https://user-images.githubusercontent.com/217898/58633503-ece58880-82e8-11e9-8202-b18020018276.png)

Background Image
![setup_page_background](https://user-images.githubusercontent.com/217898/58633504-ed7e1f00-82e8-11e9-8aa7-69abb46b8d89.jpeg)
