### ISSUE TITLE
As a user I want a Points Counter to easily count point during my turn

### ISSUE THREAD

**Issue by synasius** [evonove/volfyirion-app#45]
![Approved - Points counter](https://user-images.githubusercontent.com/217898/61387110-c8a03400-a8b5-11e9-99e4-bc5eca29326b.png)

## Description
Users want a point counter to keep track of their points during a match.
The points to keep track of are:
* knowledge
* battle
* command

## Design & Assets
Design is available at: https://www.figma.com/file/Buzigm5XdjVLpbGjEJbxNkJh/Points-counter-v2?node-id=0%3A1 (**NOTE** only the last two on the right are confirmed, the others have been discarded)

Here are the assets needed to implement the design
[pointcounterassets.zip](https://github.com/evonove/volfyirion-app/files/3386783/pointcounterassets.zip)

## Depends on
- [x] Issue #48 Data model to store points
- [x] Issue #47 Game Page
- [x] Issue #53 Square Growl Button
