### ISSUE TITLE
As a user I want a page that shows how to setup the game

### ISSUE THREAD

**Issue by synasius** [evonove/volfyirion-app#6]
Game setup page shows an image that represents how the cards should be displaced.
This page should be pushed into the stack view of the setup section (see #1 )

<img width="375" alt="game_setup" src="https://user-images.githubusercontent.com/217898/58705422-765f8e00-83af-11e9-8143-830a64d01e72.png">

# Depends on
- [x] #5 Create Volfyirion style
- [x] #7 Header Component
- [x] #4 TabBar and TabButton Component
- [x] #1 Home screen section (aka Setup)

# Assets
Card displacement
![game_setup](https://user-images.githubusercontent.com/217898/58706397-3fd74280-83b2-11e9-878d-afdd5c408a7d.png)

Volfyirion Monogram
![monogram](https://user-images.githubusercontent.com/217898/58706423-4fef2200-83b2-11e9-98c6-a1de4e892421.png)
