### ISSUE TITLE
As a user I want a page with the interactive rulebook

### ISSUE THREAD

**Issue by synasius** [evonove/volfyirion-app#8]
<img width="375" alt="rulebook_1" src="https://user-images.githubusercontent.com/217898/58784502-dfc7e280-85e3-11e9-9cdd-fa1eff44bffd.png">

Complete design is too big, look at it at this link (the item named `rulebook_2`): https://www.figma.com/file/VNQv6z1UKQbmAcxlQMhRH9pm/volfyirion_2?node-id=1%3A130

# Description
Rulebook is organized as a big single page where user can scroll through the content. 
Content is organized in a big `ObjectModel` (see #10)
Clicking on the index icon should open the index page (see #9)
Search Bar allows the user to search for some text in the content (see #11 and #12)

# Depends on
- [x] #11 create search library
- [x] #12 create search bar component
- [x] #10 create a visual model of the rulebook content
- [x] #9 create an index page that allows to navigate the rulebook
- [x] #27 add busy indicator while content is loading

# Assets
![rulebook_page_background](https://user-images.githubusercontent.com/217898/58785471-d3448980-85e5-11e9-8a53-d3e7b4e3b42c.jpeg)
![rulebook_user](https://user-images.githubusercontent.com/217898/58785473-d50e4d00-85e5-11e9-8924-16f6ee7a0a91.png)
